export default {
  WHITE: '#FFFFFF',
  BLACK: '#000000',

  // BACKGROUNDS
  DEFAULT_BACKGROUND_COLOR: '#f8f8ff',
  LIGHT_BLUE_BACKGROUND_COLOR: '#DBF1FF',
  BLUE_BACKGROUND_COLOR: '#BFD1FD',
  PURPLE_BACKGROUND_COLOR: '#D1BFFD',
  PINK_BACKGROUND_COLOR: '#F1DBFF',

  // THEME 1
  SECONDARY: '#B33771', // Orange
  LIGHT_SECONDARY: '#FEA47F',

  LIGHT_PRIMARY: '#25CCF7',
  PRIMARY: '#1B9CFC', // BLUE
  DARK_PRIMARY: '#3B3B98',

  ACTION: '#B33771', // PURPLE
  HIGHLIGHT: '#FC427B', // PINK

  // ACTIONS
  SUCCESS: '#3adb76',
  WARNING: '#ffae00',
  ALERT: '#cc4b37',

  // GRAYSCALE
  GRAY_LIGHT: '#e6e6e6',
  GRAY_MEDIUM: '#cacaca',
  GRAY_DARK: '#8a8a8a',

  TRANSPARENT: 'transparent',

  // FONT COLOR
  DEFAULT_FONT_COLOR: '#051B2B',
};
