export default {
  WHITE: '#FFFFFF',
  BLACK: '#262626',

  // BACKGROUNDS
  DEFAULT_BACKGROUND_COLOR: '#EBEAEF',
  DEFAULT_BACKGROUND_COLOR_2: '#F3F0F1',
  LIGHT_BLUE_BACKGROUND_COLOR: '#DBF1FF',
  BLUE_BACKGROUND_COLOR: '#BFD1FD',

  // THEME 1
  SECONDARY: '#F2C53D',
  SECONDARY_MUTED: '#F4D986',

  LIGHT_PRIMARY: '#79D1EB',
  PRIMARY: '#F26363', // BLUE
  DARK_PRIMARY: '#2E315C',

  ACTION: '#E91E63',
  ACTION_MUTED: '#EC6592',

  // GRAYSCALE
  GRAY_LIGHT: '#e6e6e6',
  GRAY_MEDIUM: '#cacaca',
  GRAY_DARK: '#8a8a8a',

  // ACTION COLORS
  PINK: '#EB4940',
  YELLOW: '#EBD23F',

  TRANSPARENT: 'transparent',

  PINK_MUTED: '#FACACA',
  BLUE_MUTED: '#98CAF5',
  GREEN_MUTED: '#A7E3CA',
  YELLOW_MUTED: '#FCDC9F',

  // FONT COLOR
  DEFAULT_FONT_COLOR: '#262626',
};
