export default {
  WHITE: '#FFFFFF',
  BLACK: '#000000',

  // BACKGROUNDS
  DEFAULT_BACKGROUND_COLOR: '#F2F2F2',
  LIGHT_BLUE_BACKGROUND_COLOR: '#DBF1FF',
  BLUE_BACKGROUND_COLOR: '#BFD1FD',
  PURPLE_BACKGROUND_COLOR: '#D1BFFD',
  PINK_BACKGROUND_COLOR: '#F1DBFF',

  // THEME 1
  SECONDARY: '#F2C53D',
  SECONDARY_MUTED: '#F4E27D',

  LIGHT_PRIMARY: '#ACE5F2',
  PRIMARY: '#5955D9', // BLUE
  DARK_PRIMARY: '#6573BF',

  // GRAYSCALE
  GRAY_LIGHT: '#e6e6e6',
  GRAY_MEDIUM: '#cacaca',
  GRAY_DARK: '#8a8a8a',

  TRANSPARENT: 'transparent',

  // FONT COLOR
  DEFAULT_FONT_COLOR: '#101626',
};
